# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setWindowTitle("TW bot")
        Dialog.setToolTip("")
        Dialog.setStatusTip("")
        Dialog.setWhatsThis("")
        self.spear_box = QtWidgets.QSpinBox(Dialog)
        self.spear_box.setGeometry(QtCore.QRect(130, 70, 42, 22))
        self.spear_box.setObjectName("spear_box")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 50, 41, 16))
        self.label.setObjectName("label")
        self.sword_box = QtWidgets.QSpinBox(Dialog)
        self.sword_box.setGeometry(QtCore.QRect(180, 70, 42, 22))
        self.sword_box.setObjectName("sword_box")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 50, 41, 16))
        self.label_2.setObjectName("label_2")
        self.axe_box = QtWidgets.QSpinBox(Dialog)
        self.axe_box.setGeometry(QtCore.QRect(230, 70, 42, 22))
        self.axe_box.setObjectName("axe_box")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 50, 41, 16))
        self.label_3.setObjectName("label_3")
        self.light_box = QtWidgets.QSpinBox(Dialog)
        self.light_box.setGeometry(QtCore.QRect(280, 70, 42, 22))
        self.light_box.setObjectName("light_box")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(280, 50, 41, 16))
        self.label_4.setObjectName("label_4")
        self.scout_box = QtWidgets.QSpinBox(Dialog)
        self.scout_box.setGeometry(QtCore.QRect(330, 70, 42, 22))
        self.scout_box.setObjectName("scout_box")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(330, 50, 41, 16))
        self.label_5.setObjectName("label_5")
        self.ram_box = QtWidgets.QSpinBox(Dialog)
        self.ram_box.setGeometry(QtCore.QRect(380, 70, 42, 22))
        self.ram_box.setObjectName("ram_box")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(380, 50, 41, 16))
        self.label_6.setObjectName("label_6")
        self.cata_box = QtWidgets.QSpinBox(Dialog)
        self.cata_box.setGeometry(QtCore.QRect(430, 70, 42, 22))
        self.cata_box.setObjectName("cata_box")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(430, 50, 41, 16))
        self.label_7.setObjectName("label_7")
        self.snob_box = QtWidgets.QSpinBox(Dialog)
        self.snob_box.setGeometry(QtCore.QRect(480, 70, 42, 22))
        self.snob_box.setObjectName("snob_box")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(480, 50, 41, 16))
        self.label_8.setObjectName("label_8")
        self.progress_bar = QtWidgets.QProgressBar(Dialog)
        self.progress_bar.setGeometry(QtCore.QRect(130, 20, 391, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.log_edit = QtWidgets.QPlainTextEdit(Dialog)
        self.log_edit.setGeometry(QtCore.QRect(130, 120, 391, 201))
        self.log_edit.setObjectName("log_edit")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(130, 100, 47, 21))
        self.label_9.setObjectName("label_9")
        self.go_farm_button = QtWidgets.QPushButton(Dialog)
        self.go_farm_button.setGeometry(QtCore.QRect(130, 430, 141, 23))
        self.go_farm_button.setObjectName("go_farm_button")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(130, 350, 71, 20))
        self.label_10.setObjectName("label_10")
        self.max_range_edit = QtWidgets.QLineEdit(Dialog)
        self.max_range_edit.setGeometry(QtCore.QRect(210, 350, 61, 20))
        self.max_range_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.max_range_edit.setObjectName("max_range_edit")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(220, 330, 61, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(130, 400, 71, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(210, 380, 81, 20))
        self.label_13.setObjectName("label_13")
        self.wait_time_edit = QtWidgets.QLineEdit(Dialog)
        self.wait_time_edit.setGeometry(QtCore.QRect(210, 400, 61, 20))
        self.wait_time_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.wait_time_edit.setObjectName("wait_time_edit")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(460, 330, 61, 20))
        self.label_14.setObjectName("label_14")
        self.attack_at_edit = QtWidgets.QLineEdit(Dialog)
        self.attack_at_edit.setGeometry(QtCore.QRect(460, 350, 61, 20))
        self.attack_at_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.attack_at_edit.setObjectName("attack_at_edit")
        self.attack_button = QtWidgets.QPushButton(Dialog)
        self.attack_button.setGeometry(QtCore.QRect(390, 430, 131, 23))
        self.attack_button.setObjectName("attack_button")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(390, 350, 71, 21))
        self.label_15.setObjectName("label_15")
        self.world_edit = QtWidgets.QLineEdit(Dialog)
        self.world_edit.setGeometry(QtCore.QRect(0, 20, 91, 20))
        self.world_edit.setObjectName("world_edit")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 71, 16))
        self.label_16.setObjectName("label_16")
        self.viewer = QtWidgets.QComboBox(Dialog)
        self.viewer.setGeometry(QtCore.QRect(0, 50, 91, 21))
        self.viewer.setObjectName("viewer")
        self.viewer.addItem("")
        self.viewer.addItem("")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(460, 380, 61, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.attack_on_edit = QtWidgets.QLineEdit(Dialog)
        self.attack_on_edit.setGeometry(QtCore.QRect(460, 400, 61, 20))
        self.attack_on_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.attack_on_edit.setObjectName("attack_on_edit")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(390, 400, 71, 21))
        self.label_18.setObjectName("label_18")
        self.villages_box = QtWidgets.QSpinBox(Dialog)
        self.villages_box.setGeometry(QtCore.QRect(0, 110, 42, 22))
        self.villages_box.setObjectName("villages_box")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(0, 90, 61, 21))
        self.label_19.setObjectName("label_19")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dialog", "spear"))
        self.label_2.setText(_translate("Dialog", "sword"))
        self.label_3.setText(_translate("Dialog", "axe"))
        self.label_4.setText(_translate("Dialog", "light"))
        self.label_5.setText(_translate("Dialog", "scout"))
        self.label_6.setText(_translate("Dialog", "ram"))
        self.label_7.setText(_translate("Dialog", "cata"))
        self.label_8.setText(_translate("Dialog", "snob"))
        self.label_9.setText(_translate("Dialog", "Logs:"))
        self.go_farm_button.setText(_translate("Dialog", "Go farm"))
        self.label_10.setText(_translate("Dialog", "Max range:"))
        self.max_range_edit.setText(_translate("Dialog", "2:30"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">[hh:mm]</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Wait time:"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">[min:max]</span><span style=\" font-size:10pt; vertical-align:super;\">sec</span></p></body></html>"))
        self.wait_time_edit.setText(_translate("Dialog", "160:624"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">[hh:mm:ss]</span></p></body></html>"))
        self.attack_at_edit.setText(_translate("Dialog", "7:00:00"))
        self.attack_button.setText(_translate("Dialog", "Attack"))
        self.label_15.setText(_translate("Dialog", "Attack at:"))
        self.world_edit.setText(_translate("Dialog", "pl115"))
        self.label_16.setText(_translate("Dialog", "World:"))
        self.viewer.setItemText(0, _translate("Dialog", "Chrome"))
        self.viewer.setItemText(1, _translate("Dialog", "Firefox"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">[x|y]</span></p></body></html>"))
        self.attack_on_edit.setText(_translate("Dialog", "000|000"))
        self.label_18.setText(_translate("Dialog", "Attack on:"))
        self.label_19.setText(_translate("Dialog", "Villages"))

